/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WzKHLri37jQ
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { ResponsiveLine } from "@nivo/line"

export function dashboard() {
  return (
    <div className="flex min-h-screen w-full flex-col">
      <header className="flex items-center border-b h-14 gap-4 p-4 shrink-0 lg:gap-6 lg:h-16">
        <Link className="flex items-center gap-2 font-semibold" href="#">
          <Package2Icon className="h-6 w-6" />
          <span className="">Acme Inc</span>
        </Link>
        <nav className="hidden font-medium sm:flex flex-row items-center gap-5 text-sm lg:gap-6">
          <Link className="font-bold" href="#">
            Overview
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Performance
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            RUM
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Synthetic
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Users
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Errors
          </Link>
        </nav>
        <div className="ml-auto flex items-center gap-2 lg:gap-4">
          <Button className="rounded-full" size="icon" variant="outline">
            <SearchIcon className="w-4 h-4" />
            <span className="sr-only">Search</span>
          </Button>
          <Button className="rounded-full" size="icon" variant="ghost">
            <img
              alt="Avatar"
              className="rounded-full"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32"
            />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader className="flex flex-row items-center gap-2">
              <div className="flex flex-col">
                <CardTitle className="text-base">Code Quality</CardTitle>
                <CardDescription className="text-sm">Maintainability, reliability, and security</CardDescription>
              </div>
              <Button className="rounded-full ml-auto" size="icon" variant="outline">
                <MoreHorizontalIcon className="w-4 h-4" />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </CardHeader>
            <CardContent className="flex flex-col items-center justify-center p-6">
              <CurvedlineChart className="w-full aspect-[2/1]" />
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-2">
              <div className="flex flex-col">
                <CardTitle className="text-base">Code Coverage</CardTitle>
                <CardDescription className="text-sm">Percentage of code covered by tests</CardDescription>
              </div>
              <Button className="rounded-full ml-auto" size="icon" variant="outline">
                <MoreHorizontalIcon className="w-4 h-4" />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </CardHeader>
            <CardContent className="flex flex-col items-center justify-center p-6">
              <CurvedlineChart className="w-full aspect-[2/1]" />
            </CardContent>
          </Card>
        </div>
        <div className="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader className="flex flex-row items-center gap-2">
              <div className="flex flex-col">
                <CardTitle className="text-base">Code Complexity</CardTitle>
                <CardDescription className="text-sm">Cyclomatic complexity</CardDescription>
              </div>
              <Button className="rounded-full ml-auto" size="icon" variant="outline">
                <MoreHorizontalIcon className="w-4 h-4" />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </CardHeader>
            <CardContent className="flex flex-col items-center justify-center p-6">
              <CurvedlineChart className="w-full aspect-[2/1]" />
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center gap-2">
              <div className="flex flex-col">
                <CardTitle className="text-base">Code Duplication</CardTitle>
                <CardDescription className="text-sm">Duplicated lines of code</CardDescription>
              </div>
              <Button className="rounded-full ml-auto" size="icon" variant="outline">
                <MoreHorizontalIcon className="w-4 h-4" />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </CardHeader>
            <CardContent className="flex flex-col items-center justify-center p-6">
              <CurvedlineChart className="w-full aspect-[2/1]" />
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}


function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function MoreHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  )
}


function CurvedlineChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        curve="monotoneX"
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}
